# Generated by Django 4.0.10 on 2024-12-19 16:13

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phasesDay', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_glucose', models.FloatField(default=0)),
                ('carbohydrates', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None)),
                ('annotations', models.TextField(default='', max_length=255)),
                ('hc_rations', models.FloatField(default=0)),
                ('bolus', models.FloatField(default=0)),
                ('units', models.FloatField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('foods', models.ManyToManyField(related_name='records', related_query_name='record', to='foods.foods')),
                ('phasesDay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', related_query_name='record', to='phasesDay.phasesday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', related_query_name='record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
