# Generated by Django 4.0.10 on 2024-12-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='annotations',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
