# Generated by Django 4.0.3 on 2022-04-06 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0002_records_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='foods',
            field=models.ManyToManyField(related_name='records', related_query_name='record', to='foods.foods'),
        ),
        migrations.AlterField(
            model_name='records',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', related_query_name='record', to=settings.AUTH_USER_MODEL),
        ),
    ]
