# Generated by Django 4.0.10 on 2024-12-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_records_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
