# Generated by Django 4.0.3 on 2022-04-06 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phasesDay', '0001_initial'),
        ('records', '0003_records_foods_alter_records_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='phasesDay',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='records', related_query_name='record', to='phasesDay.phasesday'),
        ),
    ]
