# Generated by Django 4.0.3 on 2022-04-06 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phasesDay', '0001_initial'),
        ('records', '0004_records_phasesday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='phasesDay',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='records', related_query_name='record', to='phasesDay.phasesday'),
        ),
    ]
