# Generated by Django 4.0.4 on 2022-05-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_rename_date_records_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='bolus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='records',
            name='hc_rations',
            field=models.FloatField(default=0),
        ),
    ]
