# Generated by Django 4.0.10 on 2024-12-19 15:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_records_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='carbohydrates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
    ]
